# Generated by Django 4.2.1 on 2023-05-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("vote_average", models.DecimalField(decimal_places=1, max_digits=3)),
                ("release_date", models.DateField()),
                ("imdb_id", models.CharField(max_length=100)),
                ("generos", models.CharField(max_length=200)),
                ("poster_link", models.URLField()),
            ],
        ),
    ]
