# Generated by Django 4.2.1 on 2023-05-23 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('vote_average', models.DecimalField(decimal_places=1, max_digits=3)),
                ('release_date', models.DateField()),
                ('imdb_id', models.CharField(max_length=100)),
                ('generos', models.CharField(max_length=200)),
                ('poster_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vista',
            fields=[
                ('idvista', models.AutoField(primary_key=True, serialize=False)),
                ('idmovie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.movie')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('idfavorito', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('idmovie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.movie')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idcomentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=200)),
                ('idmovie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.movie')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
