# Generated by Django 4.2.1 on 2023-05-22 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacion', '0003_vista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idcomentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=200)),
                ('idmovie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.movie')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
